<Project>
  <PropertyGroup>
    <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
    <LangVersion>7.3</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors>$(WarningsAsErrors);CS0618;CS0612</WarningsAsErrors>
    <DebugType>portable</DebugType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(RestoreLockedMode)' == ''">true</RestoreLockedMode>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <BaseOutputPath>$(MSBuildThisFileDirectory)artifacts\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)artifacts\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <Import Project="$(RepositoryRoot).local\Build.props" Condition="Exists('$(RepositoryRoot).local\Build.props')" />
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <TargetFrameworkRootPath Condition="'$(TargetFrameworkRootPath)' == '' and Exists('$(RepositoryRoot).local\toolchains\net48-reference-assemblies\build\.NETFramework\v4.8\PresentationFramework.dll')">$(RepositoryRoot).local\toolchains\net48-reference-assemblies\build\</TargetFrameworkRootPath>
    <RestorePackagesPath Condition="'$(RestorePackagesPath)' == '' and '$(NUGET_PACKAGES)' == '' and '$(_T7UsePortableSdk)' == 'true'">$(RepositoryRoot).local\toolchains\nuget-packages</RestorePackagesPath>
  </PropertyGroup>
</Project>
