<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="WindowsBase" />
    <ProjectReference Include="..\..\src\Core\T7.Core.csproj" />
    <ProjectReference Include="..\..\src\Desktop\T7.Desktop.csproj" />
  </ItemGroup>
</Project>
